export const Routes = {
  DASHBOARD: 'Dashboard',
  MY_TASKS: 'MyTasks',
  PROJECTS: 'Projects',
  PROJECT_TODOS: 'ProjectTodos',
  CREATE_TASK: 'CreateTask',
  CREATE_PROJECT: 'CreateProject',
  CREATE_TAG: 'CreateTag',
  TAGS_LIST: 'TagsList',
  LOGIN: 'Login',
  SIGNUP: 'Signup',
  MAIN_APP: 'MainApp',
  AUTH: 'Auth',
  ADD_PROJECT_MEMBER: 'AddProjectMember',
  TODO_DETAIL: 'TodoDetail',
  VOICE_ASSISTANT: 'VoiceAssistant',
} as const;