name: CD Pipeline

on:
  push:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      KEYSTORE_FILE: release.keystore

    steps:
      # Checkout
      - name: Checkout code
        uses: actions/checkout@v5

      # Setup Node
      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: 'yarn'

      # Install dependencies
      - name: Install dependencies
        run: yarn install

      # Setup Java
      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'

      # Cache Gradle
      - name: Cache Gradle
        uses: actions/cache@v5
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}

      # 🔐 Use secrets via env
      - name: Decode Keystore
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
        run: |
          echo "$KEYSTORE_BASE64" | base64 --decode > android/app/$KEYSTORE_FILE

      - name: Build APK
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: |
          cd android
          ./gradlew assembleRelease

      - name: Verify APK
        run: ls -la android/app/build/outputs/apk/release/

        # This step is crucial to ensure the APK was generated successfully before attempting to upload it.
      - name: Upload APK
        uses: actions/upload-artifact@v5
        with:
          name: app-release
          path: android/app/build/outputs/apk/release/app-release.apk
      
      # Setup Ruby (Fastlane)
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'

      # Install Fastlane
      - name: Install Fastlane
        run: gem install fastlane

      # Deploy to Play Store
      - name: Deploy to Play Store
        run: |
          cd android
          fastlane deploy
        env:
        #   SUPPLY_JSON_KEY_DATA: ${{ secrets.PLAY_STORE_JSON }}
          GITHUB_RUN_NUMBER: ${{ github.run_number }}

      # Optional: Upload AAB as artifact
      - name: Upload AAB
        uses: actions/upload-artifact@v5
        with:
          name: app-release-aab
          path: android/app/build/outputs/bundle/release/app-release.aab
        