name: CD Pipeline

on:
  workflow_dispatch:   # manual trigger
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Setup Node
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'yarn'

      # 3. Install dependencies
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      # 4. Setup Java (REQUIRED for Android build)
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # 5. Cache Gradle (faster builds)
      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*') }}

      # 6. Install Fastlane
      - name: Install Fastlane
        run: sudo gem install fastlane

      # 7. Run Fastlane build
      - name: Build Release
        run: |
          cd android
          fastlane build_release

      # 8. Upload APK
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
         name: app-release-apk
         path: android/app/build/outputs/apk/release/app-release.apk