name: CI Pipeline

on:
  push:
    branches: [develop]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'yarn'
      # 3. Install dependencies (faster & consistent)
      - name: Install dependencies
        run: yarn install

      # 5. Run tests (CI-safe mode)
      - name: Run tests
        run: yarn test
